### ISSUE TITLE
live demo url is not working

### ISSUE THREAD

**Issue by ManuverGujjar** [bing101/Draw-My-Code#2]
![Screenshot from 2020-11-19 16-05-24](https://user-images.githubusercontent.com/39888253/99655013-2aac1300-2a81-11eb-8871-c798955e933d.png)

**Comment by arjkashyap** [comment]
Hey.. Thanks for raising the issue. I had not updated the broken link in Read me.
The new (updated link) is https://draw-my-code.herokuapp.com/

Let me know if the issue persists
